---
- name: Add host to ssh config
  blockinfile:
    dest: /home/{{ssh_key_user}}/.ssh/config.j2
    create: true
    block: |
      Host gitlab.com
      IdentityFile /home/{{ssh_key_user}}/.ssh/id_rsa
      IdentitiesOnly yes
  tags:
    - heroku_prepare_app

- name: Create a directory for app if it does not exist
  file:
    path: /home/{{ssh_key_user}}/{{app_dir}}
    state: directory
    mode: '0755'
  tags:
    - heroku_prepare_app

- name: Clone git repository
  git:
    repo: '{{repo_name}}'
    dest: /home/{{ssh_key_user}}/{{app_dir}}
    key_file: '{{ ssh_key }}'
    update: true
  register: cloned
  tags:
    - heroku_prepare_app
